#!/usr/bin/env python3
"""
Event Mappings for NBA Database

This module defines Enum classes for NBA event types and action types
to provide readable constants for use in SQL queries.
"""

from enum import Enum


class EventType(Enum):
    """NBA event message types (eventmsgtype)."""

    MADE_SHOT = 1            # Switches (ball to defense on inbound)
    MISSED_SHOT = 2          # No change; rebound decides
    FREE_THROW = 3           # Last attempt: made → switch; missed → rebound decides
    REBOUND = 4              # Sets possession to rebounder’s team
    TURNOVER = 5             # Switches (to defense or steal team)
    FOUL = 6                 # No switch unless offensive foul → switch
    VIOLATION = 7            # Usually switch; lane violations during FT: context needed
    SUBSTITUTION = 8         # No change
    TIMEOUT = 9              # No change
    JUMP_BALL = 10           # Possession set to tip winner
    EJECTION = 11            # No change by itself
    START_OF_PERIOD = 12     # No change by itself; possession set by jump ball rule
    END_OF_PERIOD = 13       # Ends possession
    INSTANT_REPLAY = 18      # No change by itself
    STOPPAGE = 20            # No change by itself (timeout-like)


class ActionType(Enum):
    """NBA action types (eventmsgactiontype)."""

    # Made Shot actions
    JUMP_SHOT = 1
    LAYUP_SHOT = 2
    DUNK_SHOT = 3
    HOOK_SHOT = 4
    BANK_SHOT = 5
    FADEAWAY_SHOT = 6
    THREE_POINT_JUMP_SHOT = 7
    RUNNING_JUMP_SHOT = 8
    DRIVING_JUMP_SHOT = 9
    TURNAROUND_JUMP_SHOT = 10
    STEP_BACK_JUMP_SHOT = 11
    PULLUP_JUMP_SHOT = 12
    FLOATING_JUMP_SHOT = 13
    FINGER_ROLL_LAYUP = 14
    DRIVING_LAYUP = 15
    REVERSE_LAYUP = 16
    ALLEY_OOP_LAYUP = 17
    PUTBACK_LAYUP = 18
    DRIVING_DUNK = 19
    ALLEY_OOP_DUNK = 20
    PUTBACK_DUNK = 21
    REVERSE_DUNK = 22
    HOOK_SHOT_MADE = 23
    BANK_HOOK_SHOT = 24
    TURNAROUND_HOOK_SHOT = 25
    FADEAWAY_HOOK_SHOT = 26
    TIP_SHOT = 27
    CUTTING_LAYUP = 28
    CUTTING_DUNK = 29
    CUTTING_FINGER_ROLL = 30

    # Missed Shot actions (100+ series)
    JUMP_SHOT_MISSED = 101
    LAYUP_SHOT_MISSED = 102
    DUNK_SHOT_MISSED = 103
    HOOK_SHOT_MISSED = 104
    BANK_SHOT_MISSED = 105
    FADEAWAY_SHOT_MISSED = 106
    THREE_POINT_JUMP_SHOT_MISSED = 107
    RUNNING_JUMP_SHOT_MISSED = 108
    DRIVING_JUMP_SHOT_MISSED = 109
    TURNAROUND_JUMP_SHOT_MISSED = 110
    STEP_BACK_JUMP_SHOT_MISSED = 111
    PULLUP_JUMP_SHOT_MISSED = 112
    FLOATING_JUMP_SHOT_MISSED = 113
    FINGER_ROLL_LAYUP_MISSED = 114
    DRIVING_LAYUP_MISSED = 115
    REVERSE_LAYUP_MISSED = 116
    ALLEY_OOP_LAYUP_MISSED = 117
    PUTBACK_LAYUP_MISSED = 118
    DRIVING_DUNK_MISSED = 119
    ALLEY_OOP_DUNK_MISSED = 120
    PUTBACK_DUNK_MISSED = 121
    REVERSE_DUNK_MISSED = 122
    HOOK_SHOT_MISSED_ALT = 123
    BANK_HOOK_SHOT_MISSED = 124
    TURNAROUND_HOOK_SHOT_MISSED = 125
    FADEAWAY_HOOK_SHOT_MISSED = 126
    TIP_SHOT_MISSED = 127
    CUTTING_LAYUP_MISSED = 128
    CUTTING_DUNK_MISSED = 129
    CUTTING_FINGER_ROLL_MISSED = 130

    # Free Throw actions
    FREE_THROW_MADE = 133
    FREE_THROW_MISSED = 134

    # Rebound actions
    OFFENSIVE_REBOUND = 137
    DEFENSIVE_REBOUND = 138

    # Turnover actions
    STEAL = 141
    BAD_PASS = 142
    LOST_BALL = 143
    TRAVELING = 144
    THREE_SECOND_VIOLATION = 145
    FIVE_SECOND_VIOLATION = 146
    EIGHT_SECOND_VIOLATION = 147
    TWENTY_FOUR_SECOND_VIOLATION = 148
    BACKCOURT_VIOLATION = 149
    DOUBLE_DRIBBLE = 150
    OUT_OF_BOUNDS = 151
    OFFENSIVE_GOALTENDING = 152
    SHOT_CLOCK_VIOLATION = 153
    PALMING = 154
    KICKED_BALL = 155
    LANE_VIOLATION = 156
    JUMP_BALL_VIOLATION = 157
    ILLEGAL_SCREEN = 158
    ILLEGAL_ASSIST = 159
    ILLEGAL_DEFENSE = 160
    ILLEGAL_OFFENSE = 161
    ILLEGAL_SUBSTITUTION = 162
    ILLEGAL_TIMEOUT = 163
    ILLEGAL_USE_OF_HANDS = 164
    ILLEGAL_CONTACT = 165
    EXCESSIVE_TIMEOUT = 166
    DELAY_OF_GAME = 167
    TECHNICAL_FOUL = 168
    FLAGRANT_FOUL = 169
    UNSPORTSMANLIKE_FOUL = 170
    DISQUALIFYING_FOUL = 171
    FIGHTING = 172
    EJECTION_FOUL = 173
    COACH_TECHNICAL = 174
    BENCH_TECHNICAL = 175
    DELAY_OF_GAME_TECHNICAL = 176
    EXCESSIVE_TIMEOUT_TECHNICAL = 177
    ILLEGAL_DEFENSE_TECHNICAL = 178
    ILLEGAL_OFFENSE_TECHNICAL = 179
    ILLEGAL_SUBSTITUTION_TECHNICAL = 180
    ILLEGAL_TIMEOUT_TECHNICAL = 181
    ILLEGAL_USE_OF_HANDS_TECHNICAL = 182
    ILLEGAL_CONTACT_TECHNICAL = 183
    EXCESSIVE_TIMEOUT_TECHNICAL_ALT = 184
    DELAY_OF_GAME_TECHNICAL_ALT = 185
    TECHNICAL_FOUL_ALT = 186
    FLAGRANT_FOUL_ALT = 187
    UNSPORTSMANLIKE_FOUL_ALT = 188
    DISQUALIFYING_FOUL_ALT = 189
    FIGHTING_ALT = 190
    EJECTION_FOUL_ALT = 191
    COACH_TECHNICAL_ALT = 192
    BENCH_TECHNICAL_ALT = 193
    DELAY_OF_GAME_TECHNICAL_ALT2 = 194
    EXCESSIVE_TIMEOUT_TECHNICAL_ALT2 = 195
    ILLEGAL_DEFENSE_TECHNICAL_ALT = 196
    ILLEGAL_OFFENSE_TECHNICAL_ALT = 197
    ILLEGAL_SUBSTITUTION_TECHNICAL_ALT = 198
    ILLEGAL_TIMEOUT_TECHNICAL_ALT = 199
    ILLEGAL_USE_OF_HANDS_TECHNICAL_ALT = 200
